### ISSUE TITLE
运行出错，现在不更新了吗？

### ISSUE THREAD

**Issue by vpei** [DayoWong0/SSRSpeed#1]
运行出错，现在不更新了吗？

**Comment by DayoWong0** [comment]
> 运行出错，现在不更新了吗？

这是我修改的别人的项目 不是我写的。推荐使用这个 https://github.com/tindy2013/stairspeedtest-reborn

**Comment by vpei** [comment]
> > 运行出错，现在不更新了吗？
> 
> 这是我修改的别人的项目 不是我写的。推荐使用这个 https://github.com/tindy2013/stairspeedtest-reborn

你这个Python写的，直接把订阅的地址测速比较好用，这个本地Windows测试问题不大，Github云端的Linux服务器执行Python代码，提示不对。可能把云端的这个搞一下，谢谢。😁
